---
- name: Playbook para agregar usuario ansible
  hosts: "{{ target | default('all') }}"
  vars:
    ansible_local_user: "{{ user | default('ansible') }}"
  tasks:
    - name: asegurarse que existe el grupo {{ ansible_local_user }}
      group:
        name: "{{ ansible_local_user }}"
        state: present
        system: yes

    - name: add {{ ansible_local_user }} sudoers file
      copy:
        content: "%{{ ansible_local_user }} ALL=(ALL) NOPASSWD: ALL"
        dest: /etc/sudoers.d/{{ ansible_local_user }}
        validate: '/usr/sbin/visudo -cf %s'
        mode: '0440'

    - name: add user {{ ansible_local_user }}
      user:
        name: "{{ ansible_local_user }}"
        group: "{{ ansible_local_user }}"
        home: "/home/{{ ansible_local_user }}/"
        shell: /bin/bash
        state: present
        expires: -1
        system: yes
        password: "$6$IjDCEDyFra5Vjoq7$WZcjqfaFMmYGwkQ2CfScmA4L2P2udgijvLCSS5zmhawDMYbr5T7O2jxAAsJHQPeMhkywbZ0778tDKhHdHtQlw1"
      notify:
        - ansible password does not expires

    - name: Set ssh keybase login
      authorized_key:
        user: "{{ ansible_local_user }}"
        path: /home/{{ ansible_local_user }}/.ssh/authorized_keys
        key: "{{ item }}"
      with_file:
        - ansible_ssh_key.pub
      tags:
        - set_ssh_keybase_login
  handlers:
    - name: ansible password does not expires
      command: "chage -m -1 -M -1 -W -1 -E -1 {{ ansible_local_user }}"
...
